// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'catItem': string;
  'catPopover': string;
  'chooseBtn': string;
  'chooseTag': string;
  'chromeframe': string;
  'content': string;
  'desc': string;
  'detail': string;
  'highQuality': string;
  'hotList': string;
  'icon': string;
  'img': string;
  'item': string;
  'listChoose': string;
  'mask': string;
  'name': string;
  'page': string;
  'select': string;
  'songList': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
