// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_searchDetail': string;
  '_singerList': string;
  '_videoList': string;
  'album': string;
  'albumName': string;
  'albumText': string;
  'alias': string;
  'artists': string;
  'bottom': string;
  'card': string;
  'chromeframe': string;
  'content': string;
  'heartIcon': string;
  'icon': string;
  'img': string;
  'item': string;
  'keywords': string;
  'listNmuber': string;
  'loading': string;
  'man': string;
  'musicTitle': string;
  'mv': string;
  'name': string;
  'nickname': string;
  'playNumber': string;
  'right': string;
  'searchTip': string;
  'singer': string;
  'single': string;
  'songList': string;
  'split': string;
  'tab': string;
  'time': string;
  'tips': string;
  'title': string;
  'top': string;
  'user': string;
  'video': string;
  'woman': string;
}
export const cssExports: CssExports;
export default cssExports;
