// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeRouter': string;
  'chromeframe': string;
  'content': string;
  'createList': string;
  'icon': string;
  'img': string;
  'item': string;
  'list': string;
  'menu': string;
  'operator': string;
  'right': string;
  'songList': string;
}
export const cssExports: CssExports;
export default cssExports;
