// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'chromeframe': string;
  'content': string;
  'editAndDelete': string;
  'img': string;
  'left': string;
  'operator': string;
  'right': string;
  'songListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
