// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_login': string;
  'form': string;
  'img': string;
  'loginTypeBtn': string;
  'other': string;
  'pattern': string;
  'switchQrCode': string;
}
export const cssExports: CssExports;
export default cssExports;
