// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_dynamic': string;
  '_follows': string;
  'active': string;
  'chromeframe': string;
  'content': string;
  'description': string;
  'diff': string;
  'divider': string;
  'infoDescription': string;
  'infoTitle': string;
  'item': string;
  'left': string;
  'link': string;
  'linkNumber': string;
  'name': string;
  'operator': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
