// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attistsDetail': string;
  'chromeframe': string;
  'content': string;
  'img': string;
  'name': string;
  'nickName': string;
  'number': string;
  'singerDetail': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
