declare module '*.css'
declare module '*.png'
declare module '*.scss'
declare module 'less-vars-to-js'
declare module '*.json'
declare module 'video-react'
declare module 'classnames'
declare module 'Ripple'
