// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desc': string;
  'detail': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
