// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_allTopList': string;
  'chromeframe': string;
  'count': string;
  'img': string;
  'item': string;
  'name': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
