// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'code': string;
  'container': string;
  'failure': string;
  'loginSuccess': string;
  'phone': string;
  'qrLogin': string;
  'reload': string;
  'successIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
