// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_list': string;
  'chromeframe': string;
  'desc': string;
  'descWrap': string;
  'imgWrap': string;
  'listen': string;
  'name': string;
  'number': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
