// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_leaderBoard': string;
  'chromeframe': string;
  'description': string;
  'diff': string;
  'icon': string;
  'img': string;
  'item': string;
  'link': string;
  'list': string;
  'name': string;
  'number': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
