// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'content': string;
  'img': string;
  'item': string;
  'lastList': string;
  'left': string;
  'name': string;
  'number': string;
  'range': string;
  'rank': string;
  'singerList': string;
  'topItem': string;
  'topNumber': string;
  'trangle': string;
}
export const cssExports: CssExports;
export default cssExports;
