// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_mvDetail': string;
  'avatar': string;
  'btn': string;
  'chooseBtn': string;
  'chooseTag': string;
  'chromeframe': string;
  'commentList': string;
  'content': string;
  'desc': string;
  'divider': string;
  'durationms': string;
  'footer': string;
  'icon': string;
  'img': string;
  'item': string;
  'left': string;
  'liked': string;
  'list': string;
  'loadMore': string;
  'more': string;
  'mvBtn': string;
  'mvTag': string;
  'name': string;
  'nickname': string;
  'otherContent': string;
  'playCount': string;
  'playTime': string;
  'publish': string;
  'right': string;
  'rightContent': string;
  'select': string;
  'simiItem': string;
  'singer': string;
  'songDesc': string;
  'songName': string;
  'space': string;
  'time': string;
  'title': string;
  'top': string;
  'vedioGroupList': string;
  'vedioGroupListPopover': string;
  'vedioList': string;
}
export const cssExports: CssExports;
export default cssExports;
