// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_mvDetail': string;
  'avatar': string;
  'btn': string;
  'chromeframe': string;
  'commentList': string;
  'content': string;
  'desc': string;
  'footer': string;
  'left': string;
  'liked': string;
  'more': string;
  'mvBtn': string;
  'mvTag': string;
  'name': string;
  'nickname': string;
  'otherContent': string;
  'playCount': string;
  'publish': string;
  'right': string;
  'select': string;
  'simiItem': string;
  'singer': string;
  'songDesc': string;
  'songName': string;
  'space': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
