// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'desItem': string;
  'item': string;
  'select': string;
  'tag': string;
}
export const cssExports: CssExports;
export default cssExports;
