// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_collect': string;
  'album': string;
  'albumDescription': string;
  'alb@umijs/maxtem': string;
  'artists': string;
  'chromeframe': string;
  'img': string;
  'mvItem': string;
  'mvSize': string;
  'name': string;
  'player': string;
  'radioGroup': string;
  'singer': string;
  'tag': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
