// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'catCard': string;
  'chromeframe': string;
  'com': string;
  'item': string;
  'name': string;
  'nickname': string;
  'playCount': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
