// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'album': string;
  'desc': string;
  'extra': string;
  'img': string;
  'name': string;
  'tag': string;
  'topName': string;
}
export const cssExports: CssExports;
export default cssExports;
