// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_latestMusic': string;
  'chromeframe': string;
  'content': string;
  'fixed': string;
  'icon': string;
  'img': string;
  'item': string;
  'layout': string;
  'list': string;
  'loading': string;
  'month': string;
  'name': string;
  'newDiscItem': string;
  'number': string;
  'playFont': string;
  'playIcon': string;
  'radioGroup': string;
  'smallTip': string;
  'time': string;
  'title': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
