// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'album': string;
  'chromeframe': string;
  'head': string;
  'list': string;
  'singer': string;
  'space': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
