// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allArtists': string;
  'artists': string;
  'chromeframe': string;
}
export const cssExports: CssExports;
export default cssExports;
