// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'home': string;
  'icon': string;
  'list': string;
  'myMusic': string;
  'recommend': string;
}
export const cssExports: CssExports;
export default cssExports;
