// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'carousel': string;
  'chromeframe': string;
  'common': string;
  'item': string;
  'left': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
