// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_playList': string;
  'btnGroup': string;
  'chromeframe': string;
  'collection': string;
  'colorLabel': string;
  'comment': string;
  'content': string;
  'creator': string;
  'divider': string;
  'heartIcon': string;
  'img': string;
  'introduction': string;
  'label': string;
  'left': string;
  'like': string;
  'link': string;
  'markTitle': string;
  'name': string;
  'number': string;
  'operator': string;
  'page': string;
  'playAll': string;
  'playIcon': string;
  'right': string;
  'songIntroduction': string;
  'tabs': string;
  'time': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
