// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'descContent': string;
  'icon': string;
  'name': string;
  'singerCover': string;
  'singerName': string;
}
export const cssExports: CssExports;
export default cssExports;
