// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'container': string;
  'content': string;
  'dinamicContent': string;
  'divider': string;
  'friend': string;
  'from': string;
  'hotTopic': string;
  'img': string;
  'imgGroup': string;
  'item': string;
  'left': string;
  'loading': string;
  'meta': string;
  'name': string;
  'playIcon': string;
  'reload': string;
  'right': string;
  'song': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
