// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_playerLayout': string;
  'chromeframe': string;
  'comment': string;
  'commentContainer': string;
  'hide': string;
  'imgOuter': string;
  'imgOuterBorder': string;
  'imgWrap': string;
  'item': string;
  'left': string;
  'lyric': string;
  'middle': string;
  'name': string;
  'noSong': string;
  'play': string;
  'playBar': string;
  'playBarSupport': string;
  'right': string;
  'ripple': string;
  'rotate': string;
  'show': string;
  'singer': string;
  'stop': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
