// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_mv': string;
  'chromeframe': string;
  'durationms': string;
  'icon': string;
  'img': string;
  'item': string;
  'mvList': string;
  'playTime': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
