// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'content': string;
  'down': string;
  'img': string;
  'item': string;
  'left': string;
  'list': string;
  'name': string;
  'number': string;
  'playIcon': string;
  'right': string;
  'score': string;
  'top': string;
  'topMv': string;
  'up': string;
}
export const cssExports: CssExports;
export default cssExports;
