// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
