// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { connect, useDispatch, useStore, useSelector, getDvaApp } from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-dva';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-locale';
export { Provider, useModel } from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-antd/types.d';
export * from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-dva/types.d';
export * from '/Users/01429034/douya/react-web-cloud-music/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/01429034/douya/react-web-cloud-music/node_modules/.pnpm/@umijs+renderer-react@4.1.5_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/01429034/douya/react-web-cloud-music/node_modules/.pnpm/@umijs+renderer-react@4.1.5_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/01429034/douya/react-web-cloud-music/node_modules/.pnpm/umi@4.1.5_@babel+core@7.24.3_@types+node@20.11.30_@types+react@16.14.59_eslint@8.35.0_prettie_n7u7p4odx3a6m34n4py52acndi/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
