// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exclusiveBroadcast': string;
  'img': string;
  'loading': string;
  'name': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
