// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from '/Users/01429034/douya/react-web-cloud-music/node_modules/.pnpm/@umijs+plugins@4.1.5_@babel+core@7.24.3_@types+react-dom@16.9.24_@types+react@16.14.59_antd@4_yt3ijp7stzomzpend3zmnvmbhy/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
