// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/01429034/douya/react-web-cloud-music/src/models/playStore';
import model_2 from '/Users/01429034/douya/react-web-cloud-music/src/models/songInfoStore';
import model_3 from '/Users/01429034/douya/react-web-cloud-music/src/models/userStore';

export const models = {
model_1: { namespace: 'playStore', model: model_1 },
model_2: { namespace: 'songInfoStore', model: model_2 },
model_3: { namespace: 'userStore', model: model_3 },
} as const
