// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'commentList': string;
  'content': string;
  'footer': string;
  'more': string;
  'nickname': string;
  'otherContent': string;
  'time': string;
}
export const cssExports: CssExports;
export default cssExports;
