// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alias': string;
  'card': string;
  'chromeframe': string;
  'descContent': string;
  'diff': string;
  'divider': string;
  'img': string;
  'item': string;
  'left': string;
  'list': string;
  'name': string;
  'number': string;
  'playCount': string;
  'playIcon': string;
  'playTime': string;
  'publishTime': string;
  'right': string;
  'showAll': string;
  'singerCover': string;
  'singerName': string;
  'space': string;
  'tableCardLayout': string;
  'tableItem': string;
  'tableLaout': string;
  'time': string;
  'titile': string;
}
export const cssExports: CssExports;
export default cssExports;
