// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_edit_song_list': string;
  'addLabel': string;
  'chromeframe': string;
  'content': string;
  'description': string;
  'divider': string;
  'footBtn': string;
  'footer': string;
  'form': string;
  'img': string;
  'item': string;
  'label': string;
  'labelList': string;
  'left': string;
  'number': string;
  'right': string;
  'tag': string;
  'tip': string;
  'title': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
