// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addLabel': string;
  'chromeframe': string;
  'description': string;
  'editSongList': string;
  'footer': string;
  'img': string;
  'item': string;
  'label': string;
  'labelList': string;
  'left': string;
  'number': string;
  'right': string;
  'submitFooter': string;
  'tag': string;
  'tip': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
