// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_newMusic': string;
  'chromeframe': string;
  'content': string;
  'icon': string;
  'img': string;
  'name': string;
  'number': string;
  'playIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
