// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_personalRecommendation': string;
  'link': string;
  'newMusic': string;
  'recommend': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
