// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chromeframe': string;
  'img': string;
  'item': string;
  'simi': string;
}
export const cssExports: CssExports;
export default cssExports;
