// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_footer': string;
  '_homeDiff': string;
  'bottom': string;
  'caret': string;
  'chromeframe': string;
  'collapsed': string;
  'common': string;
  'content': string;
  'drawer': string;
  'footer': string;
  'footerContainer': string;
  'full': string;
  'home': string;
  'img': string;
  'info': string;
  'mask': string;
  'move': string;
  'name': string;
  'now': string;
  'operating': string;
  'pause': string;
  'playBtnGroup': string;
  'playRate': string;
  'progress': string;
  'slider': string;
  'songName': string;
  'split': string;
  'tip': string;
  'top': string;
  'voice': string;
}
export const cssExports: CssExports;
export default cssExports;
