// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_playRecord': string;
  'chromeframe': string;
  'delete': string;
  'divider': string;
  'header': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
