// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'number': string;
  'topNumber': string;
  'trangle': string;
}
export const cssExports: CssExports;
export default cssExports;
