// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exclusiveBroadcastItem': string;
  'icon': string;
  'img': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
