name: web-music-build #action名称
on: [push] #在推送的时候运行此action
push:
    branches:
      - feature/v2.0 #当feature/v2.0分支推送的时候,我们部署到生产服务器

jobs:
  build_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2    #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build