name: 自动部署 #action名称
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest # 指定用什么版本服务器来执行

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2

      - name: 指定node版本
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: 将npm配置为使用 https
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: 安装依赖
        run: npm i

      - name: 编译构建
        run: npm run build

      - name: 删除服务器文件
        uses: appleboy/ssh-action@master
        with:
          # 这里配置对应仓库设置的变量，就可以避免服务器配置暴露
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}

          # 先用 SSH 命令删除旧文件
          script: |
             rm -rf /usr/local/nginx/html/*
             mkdir  /usr/local/nginx/html/iconfont
             mkdir  /usr/local/nginx/html/static
      

      - name: 打包文件推送到服务器--1
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 这个是sftp插件
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          local_path: './dist/*'
          remote_path: '/usr/local/nginx/html'
